//
// File generated by /afs/ihep.ac.cn/soft/juno/JUNO-ALL/Pre-Release/J14v1r1-pre1/ExternalLibs/ROOT/5.34.11/bin/rootcint at Mon Jan 26 15:17:17 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdOdIsrcdIJobInfoDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JobInfoDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void JobInfo_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JobInfo(void *p = 0);
   static void *newArray_JobInfo(Long_t size, void *p);
   static void delete_JobInfo(void *p);
   static void deleteArray_JobInfo(void *p);
   static void destruct_JobInfo(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::JobInfo*)
   {
      ::JobInfo *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JobInfo >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JobInfo", ::JobInfo::Class_Version(), "./JobInfo.h", 8,
                  typeid(::JobInfo), DefineBehavior(ptr, ptr),
                  &::JobInfo::Dictionary, isa_proxy, 4,
                  sizeof(::JobInfo) );
      instance.SetNew(&new_JobInfo);
      instance.SetNewArray(&newArray_JobInfo);
      instance.SetDelete(&delete_JobInfo);
      instance.SetDeleteArray(&deleteArray_JobInfo);
      instance.SetDestructor(&destruct_JobInfo);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::JobInfo*)
   {
      return GenerateInitInstanceLocal((::JobInfo*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JobInfo*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *JobInfo::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *JobInfo::Class_Name()
{
   return "JobInfo";
}

//______________________________________________________________________________
const char *JobInfo::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JobInfo*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int JobInfo::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::JobInfo*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void JobInfo::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JobInfo*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *JobInfo::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::JobInfo*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void JobInfo::Streamer(TBuffer &R__b)
{
   // Stream an object of class JobInfo.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(JobInfo::Class(),this);
   } else {
      R__b.WriteClassBuffer(JobInfo::Class(),this);
   }
}

//______________________________________________________________________________
void JobInfo::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JobInfo.
      TClass *R__cl = ::JobInfo::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_jobOption", (void*)&m_jobOption);
      R__insp.InspectMember("string", (void*)&m_jobOption, "m_jobOption.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_offlineVersion", (void*)&m_offlineVersion);
      R__insp.InspectMember("string", (void*)&m_offlineVersion, "m_offlineVersion.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_refCount", &m_refCount);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_JobInfo(void *p) {
      return  p ? new(p) ::JobInfo : new ::JobInfo;
   }
   static void *newArray_JobInfo(Long_t nElements, void *p) {
      return p ? new(p) ::JobInfo[nElements] : new ::JobInfo[nElements];
   }
   // Wrapper around operator delete
   static void delete_JobInfo(void *p) {
      delete ((::JobInfo*)p);
   }
   static void deleteArray_JobInfo(void *p) {
      delete [] ((::JobInfo*)p);
   }
   static void destruct_JobInfo(void *p) {
      typedef ::JobInfo current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::JobInfo

/********************************************************
* ../src/JobInfoDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJobInfoDict();

extern "C" void G__set_cpp_environmentJobInfoDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JobInfo.h");
  G__cpp_reset_tagtableJobInfoDict();
}
#include <new>
extern "C" int G__cpp_dllrevJobInfoDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JobInfo */
static int G__JobInfoDict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JobInfo* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JobInfo[n];
     } else {
       p = new((void*) gvp) JobInfo[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JobInfo;
     } else {
       p = new((void*) gvp) JobInfo;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((const JobInfo*) G__getstructoffset())->getJobOption();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((const JobInfo*) G__getstructoffset())->getOfflineVersion();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JobInfo*) G__getstructoffset())->setJobOption(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JobInfo*) G__getstructoffset())->setOfflineVersion(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JobInfo*) G__getstructoffset())->addRef();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JobInfo*) G__getstructoffset())->decRef();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JobInfo::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JobInfo::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JobInfo::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JobInfo::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JobInfo*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JobInfo::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JobInfo::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JobInfo::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JobInfoDict_168_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JobInfo::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__JobInfoDict_168_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JobInfo* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JobInfo(*(JobInfo*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JobInfo G__TJobInfo;
static int G__JobInfoDict_168_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JobInfo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JobInfo*) (soff+(sizeof(JobInfo)*i)))->~G__TJobInfo();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JobInfo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JobInfo*) (soff))->~G__TJobInfo();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__JobInfoDict_168_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JobInfo* dest = (JobInfo*) G__getstructoffset();
   *dest = *(JobInfo*) libp->para[0].ref;
   const JobInfo& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JobInfo */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJobInfoDict {
 public:
  G__Sizep2memfuncJobInfoDict(): p(&G__Sizep2memfuncJobInfoDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJobInfoDict::*p)();
};

size_t G__get_sizep2memfuncJobInfoDict()
{
  G__Sizep2memfuncJobInfoDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJobInfoDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo))) {
     JobInfo *G__Lderived;
     G__Lderived=(JobInfo*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo),G__get_linked_tagnum(&G__JobInfoDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJobInfoDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JobInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JobInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JobInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JobInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JobInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JobInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JobInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JobInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JobInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JobInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JobInfo */
static void G__setup_memvarJobInfo(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo));
   { JobInfo *p; p=(JobInfo*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JobInfoDictLN_string),-1,-1,4,"m_jobOption=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__JobInfoDictLN_string),-1,-1,4,"m_offlineVersion=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_refCount=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JobInfoDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJobInfoDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJobInfo(void) {
   /* JobInfo */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo));
   G__memfunc_setup("JobInfo",679,G__JobInfoDict_168_0_1, 105, G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getJobOption",1236,G__JobInfoDict_168_0_2, 117, G__get_linked_tagnum(&G__JobInfoDictLN_string), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getOfflineVersion",1769,G__JobInfoDict_168_0_3, 117, G__get_linked_tagnum(&G__JobInfoDictLN_string), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setJobOption",1248,G__JobInfoDict_168_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setOfflineVersion",1781,G__JobInfoDict_168_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addRef",582,G__JobInfoDict_168_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("decRef",585,G__JobInfoDict_168_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__JobInfoDict_168_0_8, 85, G__get_linked_tagnum(&G__JobInfoDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JobInfo::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__JobInfoDict_168_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JobInfo::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__JobInfoDict_168_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JobInfo::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__JobInfoDict_168_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JobInfo::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__JobInfoDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__JobInfoDict_168_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__JobInfoDict_168_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JobInfo::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__JobInfoDict_168_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JobInfo::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__JobInfoDict_168_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JobInfo::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__JobInfoDict_168_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JobInfo::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("JobInfo", 679, G__JobInfoDict_168_0_20, (int) ('i'), G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo), -1, 0, 1, 1, 1, 0, "u 'JobInfo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JobInfo", 805, G__JobInfoDict_168_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__JobInfoDict_168_0_22, (int) ('u'), G__get_linked_tagnum(&G__JobInfoDictLN_JobInfo), -1, 1, 1, 1, 1, 0, "u 'JobInfo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJobInfoDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJobInfoDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJobInfoDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JobInfoDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JobInfoDictLN_JobInfo = { "JobInfo" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJobInfoDict() {
  G__JobInfoDictLN_TClass.tagnum = -1 ;
  G__JobInfoDictLN_TBuffer.tagnum = -1 ;
  G__JobInfoDictLN_TMemberInspector.tagnum = -1 ;
  G__JobInfoDictLN_TObject.tagnum = -1 ;
  G__JobInfoDictLN_string.tagnum = -1 ;
  G__JobInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JobInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JobInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JobInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JobInfoDictLN_JobInfo.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJobInfoDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_string);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JobInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JobInfoDictLN_JobInfo),sizeof(JobInfo),-1,292096,(char*)NULL,G__setup_memvarJobInfo,G__setup_memfuncJobInfo);
}
extern "C" void G__cpp_setupJobInfoDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJobInfoDict()");
  G__set_cpp_environmentJobInfoDict();
  G__cpp_setup_tagtableJobInfoDict();

  G__cpp_setup_inheritanceJobInfoDict();

  G__cpp_setup_typetableJobInfoDict();

  G__cpp_setup_memvarJobInfoDict();

  G__cpp_setup_memfuncJobInfoDict();
  G__cpp_setup_globalJobInfoDict();
  G__cpp_setup_funcJobInfoDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJobInfoDict();
  return;
}
class G__cpp_setup_initJobInfoDict {
  public:
    G__cpp_setup_initJobInfoDict() { G__add_setup_func("JobInfoDict",(G__incsetup)(&G__cpp_setupJobInfoDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJobInfoDict() { G__remove_setup_func("JobInfoDict"); }
};
G__cpp_setup_initJobInfoDict G__cpp_setup_initializerJobInfoDict;

