/********************************************************************
* ../src/JobInfoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/JobInfoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableJobInfoDict();
extern void G__cpp_setup_inheritanceJobInfoDict();
extern void G__cpp_setup_typetableJobInfoDict();
extern void G__cpp_setup_memvarJobInfoDict();
extern void G__cpp_setup_globalJobInfoDict();
extern void G__cpp_setup_memfuncJobInfoDict();
extern void G__cpp_setup_funcJobInfoDict();
extern void G__set_cpp_environmentJobInfoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JobInfo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__JobInfoDictLN_TClass;
extern G__linked_taginfo G__JobInfoDictLN_TBuffer;
extern G__linked_taginfo G__JobInfoDictLN_TMemberInspector;
extern G__linked_taginfo G__JobInfoDictLN_TObject;
extern G__linked_taginfo G__JobInfoDictLN_string;
extern G__linked_taginfo G__JobInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__JobInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JobInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__JobInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__JobInfoDictLN_JobInfo;

/* STUB derived class for protected member access */
